#
# Various reference manuals
#
SRCROOT		= ..
WEB_HOME_BASE	= refs
SUBPROJECTS	= kernel gsh

include $(SRCROOT)/etc/const-priv.mk
include $(SRCROOT)/etc/const.mk
-include $(SRCROOT)/etc/const-local.mk

include $(SRCROOT)/etc/rules.mk
