#
# Kernel Reference Manual
#
SRCROOT 	= ../..
WEB_HOME_BASE	= refs/kernel
SUBPROJECTS	= 

TEX_SRC_BASENAME = kern
TEX_TITLE	 = GNO Kernel Reference Manual

include $(SRCROOT)/etc/const-priv.mk
include $(SRCROOT)/etc/const.mk
include $(SRCROOT)/etc/const-tex.mk
-include $(SRCROOT)/etc/const-local.mk

include $(SRCROOT)/etc/rules.mk
include $(SRCROOT)/etc/rules-tex.mk

buildLocal::	texBuild
